# Dockerfile
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# instalar dependencias del sistema necesarias para psycopg2 y builds
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev postgresql-client curl \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade pip setuptools wheel \
 && pip install --no-cache-dir -r requirements.txt

COPY . .

# Asegurar que el script wait-for-db sea ejecutable dentro de la imagen
RUN if [ -f ./wait-for-db.sh ]; then chmod +x ./wait-for-db.sh; fi

# Crear directorios para archivos estáticos y media
RUN mkdir -p /vol/static /vol/media

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

