# Dockerfile
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# instalar dependencias del sistema necesarias para psycopg2 y builds
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev curl \
 && rm -rf /var/lib/apt/lists/*

# copiar requirements e instalar
COPY requirements.txt .
# Si usás pip-compile/poetry adaptá esta parte
RUN pip install --upgrade pip setuptools wheel \
 && pip install --no-cache-dir -r requirements.txt

# copiar el código
COPY . .

# crear carpeta para archivos estáticos (si usás collectstatic)
RUN mkdir -p /vol/static /vol/media

# Exponer puerto app (gunicorn)
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

